language: objective-c
osx_image: xcode9.3
gemfile: Gemfile
bundler_args: "--without documentation --path bundle"
cache:
  bundler: true
  directories:
  - "/tmp/SwiftLint"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
- "./Submodules/WeTransfer-iOS-CI/Scripts/travis.sh WeTransfer"
before_install:
- openssl aes-256-cbc -K $encrypted_1877fe15fc77_key -iv $encrypted_1877fe15fc77_iv
  -in Secrets.plist.enc -out WeTransferTests/Secrets.plist -d
